### PR TITLE
footer: implemented g0thman

### PR DESCRIPTION
**Pull request by anixide**

### CODE REVIEW

**Comment by Nwokochahannah** [comment]
Please the footer should be merged to the page you are working on

**Comment by Nwokochahannah** [comment]
You can fork the repo of the person who made the remaining page and create a PR to his repo when he merges and the code is complete he should then send a PR

**Comment by anixide** [comment]
I was only able to find and fork your repo, all the other contributions are still commits, should i like copy/paste the code of the contributors and add my footer?

**Comment by Nwokochahannah** [comment]
Which page are you working on? Facilities or room or landing page

**Comment by anixide** [comment]
It only says "footer"
image

**Pull request closed without merging**
