### PR TITLE
first commit for design 2 page 4

### PR DESCRIPTION
**Pull request by Abdulazeeza**

### CODE REVIEW

**Comment by Nwokochahannah** [comment]
Please follow the naming convention for your commit message and add pictures of your work under the description when sending the PR. Thanks

**Comment by Abdulazeeza** [comment]
Please explain how you want us to go about it step by step on the readme
file cause not all of us understands the structure you are talking about.
This way it would save you stress and time. Thank you

**Comment by Nwokochahannah** [comment]
I should have done that before but it escaped my mind, but it has been done
now

**Comment by Nwokochahannah** [comment]
Your commit message did not still follow the naming convention

**Pull request closed without merging**
